import 'dart:async';
import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:tin/core/services/mcp/kelivo_termux/kelivo_termux_server.dart';

void main() {
  group('KelivoTermuxMcpServerEngine', () {
    test('lists generic and specialized tools', () async {
      final engine = KelivoTermuxMcpServerEngine(isSupported: () => true); addTearDown(engine.close);
      final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 1, 'method': 'tools/list'}) as Map<String, dynamic>;
      final tools = response['result']['tools'] as List;
      expect(tools, hasLength(20));
      expect(tools.map((item) => (item as Map)['name']), containsAll(['termux_run_command', 'termux_get_system_info', 'termux_git_status', 'termux_download_file', 'termux_adb_shell', 'termux_run_python']));
    });
    test('maps Git status to external command interface', () async {
      late Map<String, dynamic> received;
      final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) async { received = {'command': command, 'arguments': arguments, 'workingDirectory': workingDirectory, 'background': background}; return {'success': true, 'exitCode': 0, 'stdout': 'ok', 'stderr': ''}; }); addTearDown(engine.close);
      final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 2, 'method': 'tools/call', 'params': {'name': 'termux_git_status', 'arguments': {'repository': '/storage/emulated/0/TIN'}}}) as Map<String, dynamic>;
      expect(received, containsPair('command', 'git')); expect(received['arguments'], ['status', '--short', '--branch']); expect(received['background'], isTrue); expect(response['result']['isError'], isFalse);
    });
    test('marks command failure', () async { final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) async => {'success': false, 'exitCode': 2, 'stdout': '', 'stderr': 'bad'}); addTearDown(engine.close); final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 3, 'method': 'tools/call', 'params': {'name': 'termux_run_command', 'arguments': {'command': 'git'}}}) as Map<String, dynamic>; final result = response['result'] as Map; final payload = jsonDecode(result['content'][0]['text'] as String) as Map; expect(result['isError'], isTrue); expect(payload['stderr'], 'bad'); });
    test('rejects invalid paths before Android', () async { var invoked = false; final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) async { invoked = true; return {}; }); addTearDown(engine.close); final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 4, 'method': 'tools/call', 'params': {'name': 'termux_git_status', 'arguments': {'repository': '/data/local/tmp'}}}) as Map<String, dynamic>; expect(invoked, isFalse); expect(response['result']['isError'], isTrue); });
    test('rejects oversized specialized arguments', () async { var invoked = false; final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) async { invoked = true; return {}; }); addTearDown(engine.close); final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 5, 'method': 'tools/call', 'params': {'name': 'termux_run_python', 'arguments': {'script': '/storage/emulated/0/script.py', 'arguments': List<String>.filled(64, 'x')}}}) as Map<String, dynamic>; expect(invoked, isFalse); expect(response['result']['isError'], isTrue); });
    test('rejects Git option injection', () async { var invoked = false; final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) async { invoked = true; return {}; }); addTearDown(engine.close); final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 6, 'method': 'tools/call', 'params': {'name': 'termux_git_fetch', 'arguments': {'repository': '/storage/emulated/0/TIN', 'remote': '--upload-pack=bad'}}}) as Map<String, dynamic>; expect(invoked, isFalse); expect(response['result']['isError'], isTrue); });
    test('stops commit when staging fails', () async { final calls = <List<String>>[]; final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) async { calls.add(arguments); return {'success': false, 'exitCode': 1, 'stdout': '', 'stderr': 'failed'}; }); addTearDown(engine.close); final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 7, 'method': 'tools/call', 'params': {'name': 'termux_git_commit', 'arguments': {'repository': '/storage/emulated/0/TIN', 'paths': ['missing'], 'message': 'test'}}}) as Map<String, dynamic>; expect(calls, [['add', '--', 'missing']]); expect(response['result']['isError'], isTrue); });
    test('maps timeout to stable error', () async { final engine = KelivoTermuxMcpServerEngine(isSupported: () => true, executor: ({required command, required arguments, required workingDirectory, required background, required timeoutSeconds}) => throw TimeoutException('late')); addTearDown(engine.close); final response = await engine.handleMessage({'jsonrpc': '2.0', 'id': 8, 'method': 'tools/call', 'params': {'name': 'termux_run_command', 'arguments': {'command': 'sleep'}}}) as Map<String, dynamic>; expect(response['result']['content'][0]['text'], contains('termux_timeout')); });
  });
}
