import 'dart:convert';

/// Reuses an in-flight or completed successful result for an identical call.
///
/// The key includes the tool name and the complete recursively normalized
/// argument map. Different URLs, pages, headers, or split subtasks therefore
/// remain independent. Results that represent tool errors, and thrown
/// exceptions, are removed so a later request can retry them.
class ToolCallResultCache {
  final Map<String, Future<String>> _results = <String, Future<String>>{};

  /// Returns an in-flight or completed result for [name] and [args].
  ///
  /// Only explicitly read-only web/search tools are eligible. This prevents
  /// memory, app-control, local, and arbitrary MCP mutations from being
  /// replayed from a previous result.
  Future<String>? lookup(String name, Map<String, dynamic> args) {
    if (!ToolLoopGuard.isReadOnlyCacheTool(name)) return null;
    return _results[ToolLoopGuard.signatureOf(name, args)];
  }

  /// Executes [run] once for one signature while it is in flight, then reuses
  /// its successful result for the rest of the assistant response.
  Future<String> run(
    String name,
    Map<String, dynamic> args,
    Future<String> Function() execute,
  ) {
    if (!ToolLoopGuard.isReadOnlyCacheTool(name)) return execute();

    final signature = ToolLoopGuard.signatureOf(name, args);
    final cached = _results[signature];
    if (cached != null) return cached;

    late final Future<String> pending;
    pending = _runAndKeepSuccessfulResult(
      signature,
      execute,
      () => pending,
    );
    _results[signature] = pending;
    return pending;
  }

  Future<String> _runAndKeepSuccessfulResult(
    String signature,
    Future<String> Function() execute,
    Future<String> Function() current,
  ) async {
    try {
      final result = await execute();
      if (!ToolLoopGuard.isCacheableResult(result) &&
          identical(_results[signature], current())) {
        _results.remove(signature);
      }
      return result;
    } catch (_) {
      if (identical(_results[signature], current())) {
        _results.remove(signature);
      }
      rethrow;
    }
  }
}

/// Per-response tool loop accounting.
///
/// Tool call counts are intentionally unbounded: an assistant response may
/// request tools as many times as the model needs. [evaluate] always allows
/// the call and only maintains a per-response counter for observability.
class ToolLoopGuard {
  static const Set<String> _readOnlyCacheTools = <String>{
    'search_web',
    'fetch_html',
    'fetch_markdown',
    'fetch_txt',
    'fetch_json',
    // Names generated by buildFunctionCallToolName for @kelivo/fetch.
    'tool__kelivo_fetch_html',
    'tool__kelivo_fetch_markdown',
    'tool__kelivo_fetch_txt',
    'tool__kelivo_fetch_json',
    // Keep the single-underscore form compatible with existing registrations.
    'tool_kelivo_fetch_html',
    'tool_kelivo_fetch_markdown',
    'tool_kelivo_fetch_txt',
    'tool_kelivo_fetch_json',
  };

  int _calls = 0;

  /// Tool calls requested so far in the current assistant response.
  int get callCount => _calls;

  /// Builds a stable signature for one tool call.
  static String signatureOf(String name, Map<String, dynamic> args) {
    return '$name\u0000${jsonEncode(_stableValue(args))}';
  }

  /// Returns whether [name] is an explicitly read-only web/search tool.
  static bool isReadOnlyCacheTool(String name) {
    final normalized = name.trim().toLowerCase().replaceAll('-', '_');
    return _readOnlyCacheTools.contains(normalized);
  }

  /// Returns whether a result is safe to reuse for an identical later call.
  static bool isCacheableResult(String raw) {
    try {
      final decoded = jsonDecode(raw);
      if (decoded is! Map) return true;
      if (decoded['type'] == 'tool_error' ||
          decoded['tool_error'] != null ||
          decoded['isError'] == true ||
          decoded['error'] != null) {
        return false;
      }
    } catch (_) {
      // Plain text is a valid successful tool result.
    }
    return true;
  }

  /// Decides whether a tool call may run.
  ///
  /// Tool calls are unlimited: every requested call is allowed and recorded
  /// in [callCount]. [cached] is accepted for compatibility with the result
  /// cache flow and does not change the outcome.
  String? evaluate(
    String name,
    Map<String, dynamic> args, {
    bool cached = false,
  }) {
    _calls += 1;
    return null;
  }

  static Object? _stableValue(Object? value) {
    if (value is Map) {
      final keys = value.keys.map((k) => k.toString()).toList()..sort();
      return <String, Object?>{for (final k in keys) k: _stableValue(value[k])};
    }
    if (value is Iterable) return value.map(_stableValue).toList();
    if (value is num || value is bool || value == null) return value;
    return value.toString();
  }
}